version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: be_sustainable_db
    environment:
      POSTGRES_DB: be_sustainable
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: be_sustainable_backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=be_sustainable
      - JWT_SECRET=your-super-secret-key-change-this-in-production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install --include=dev && npm run dev"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge